### ISSUE TITLE
Agendamientos

### ISSUE THREAD

**Issue by haideg** [ProyectoINCAN/Proyecto#14]

**Comment by haideg** [comment]
# Agendamientos Detalle
[ ]  modal de agendamientos detalle

[ ] boton de pasar del mismo listado de agendamientos para usuario Administrativo

**Comment by josemariaduarte** [comment]
Cambiar la creacion de un nuevo detalle de agenda.

- Al iniciar mostrar el listado de pacientes.

- En caso de no estar registrado se crea un nuevo paciente.

- Aparece la opcion para agregar el detalle dentro de datatable
