### ISSUE TITLE
Agendamientos

### ISSUE THREAD

**Issue by fabianpy** [ProyectoINCAN/Proyecto#3]
Al agregar una nueva agenda, sería interesante seleccionar primero el médico y luego la especialidad. O que al seleccionar un médico, ya traiga la especialidad.

**Comment by fabianpy** [comment]
Se debe restringir que una persona no se pueda registrar más de una vez en la misma agenda detalle

**Comment by fabianpy** [comment]
Se debe tener un listado de todas las agendas pendientes para que el usuario seleccione la agenda que quiere cancelar.

**Comment by josemariaduarte** [comment]
cerrado
